# Generated by Django 6.0.3 on 2026-03-12 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessments',
            fields=[
                ('assessmentID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Assessments',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('deptID', models.AutoField(primary_key=True, serialize=False)),
                ('deptName', models.CharField(max_length=255)),
                ('collegeName', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Department',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('fullName', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('roleType', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('skillID', models.AutoField(primary_key=True, serialize=False)),
                ('skillName', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'Skills',
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('userID', models.OneToOneField(db_column='userID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.users')),
                ('title', models.CharField(max_length=255)),
                ('deptID', models.ForeignKey(db_column='deptID', on_delete=django.db.models.deletion.RESTRICT, to='users.department')),
            ],
            options={
                'db_table': 'Faculty',
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('questionID', models.AutoField(primary_key=True, serialize=False)),
                ('questionText', models.TextField()),
                ('questionType', models.CharField(max_length=50)),
                ('correctAnswer', models.TextField(blank=True, null=True)),
                ('points', models.IntegerField()),
                ('assessmentID', models.ForeignKey(db_column='assessmentID', on_delete=django.db.models.deletion.CASCADE, to='users.assessments')),
            ],
            options={
                'db_table': 'Questions',
            },
        ),
        migrations.CreateModel(
            name='ResearchPostings',
            fields=[
                ('postingID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('prerequisites', models.TextField(blank=True, null=True)),
                ('requiredGPA', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=50)),
                ('deadline', models.DateField()),
                ('deptID', models.ForeignKey(db_column='deptID', on_delete=django.db.models.deletion.RESTRICT, to='users.department')),
                ('facultyID', models.ForeignKey(db_column='facultyID', on_delete=django.db.models.deletion.CASCADE, to='users.faculty')),
            ],
            options={
                'db_table': 'ResearchPostings',
            },
        ),
        migrations.AddField(
            model_name='assessments',
            name='postingID',
            field=models.ForeignKey(db_column='postingID', on_delete=django.db.models.deletion.CASCADE, to='users.researchpostings'),
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('studentID', models.AutoField(primary_key=True, serialize=False)),
                ('major', models.CharField(max_length=255)),
                ('graduationYear', models.IntegerField()),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('deptID', models.ForeignKey(db_column='deptID', on_delete=django.db.models.deletion.RESTRICT, to='users.department')),
                ('userID', models.OneToOneField(db_column='userID', on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
            options={
                'db_table': 'Students',
            },
        ),
        migrations.CreateModel(
            name='AssessmentAttempts',
            fields=[
                ('attemptID', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
                ('passed', models.BooleanField(blank=True, null=True)),
                ('attemptDate', models.DateTimeField(auto_now_add=True)),
                ('assessmentID', models.ForeignKey(db_column='assessmentID', on_delete=django.db.models.deletion.CASCADE, to='users.assessments')),
                ('studentID', models.ForeignKey(db_column='studentID', on_delete=django.db.models.deletion.CASCADE, to='users.students')),
            ],
            options={
                'db_table': 'AssessmentAttempts',
            },
        ),
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('applicationID', models.AutoField(primary_key=True, serialize=False)),
                ('submissionDate', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('prerequisitesVerified', models.BooleanField(default=False)),
                ('postingID', models.ForeignKey(db_column='postingID', on_delete=django.db.models.deletion.CASCADE, to='users.researchpostings')),
                ('studentID', models.ForeignKey(db_column='studentID', on_delete=django.db.models.deletion.CASCADE, to='users.students')),
            ],
            options={
                'db_table': 'Applications',
            },
        ),
        migrations.CreateModel(
            name='PostingSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postingID', models.ForeignKey(db_column='postingID', on_delete=django.db.models.deletion.CASCADE, to='users.researchpostings')),
                ('skillID', models.ForeignKey(db_column='skillID', on_delete=django.db.models.deletion.CASCADE, to='users.skills')),
            ],
            options={
                'db_table': 'PostingSkills',
                'unique_together': {('postingID', 'skillID')},
            },
        ),
        migrations.CreateModel(
            name='StudentSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiencyLevel', models.CharField(blank=True, max_length=50, null=True)),
                ('skillID', models.ForeignKey(db_column='skillID', on_delete=django.db.models.deletion.CASCADE, to='users.skills')),
                ('studentID', models.ForeignKey(db_column='studentID', on_delete=django.db.models.deletion.CASCADE, to='users.students')),
            ],
            options={
                'db_table': 'StudentSkills',
                'unique_together': {('studentID', 'skillID')},
            },
        ),
    ]
