# Generated by Django 6.0.3 on 2026-04-04 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='applications',
            name='statementOfInterest',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='researchpostings',
            name='minAssessmentScore',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applications',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('under_review', 'Under Review')], max_length=50),
        ),
        migrations.AlterField(
            model_name='assessmentattempts',
            name='score',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='questions',
            name='questionType',
            field=models.CharField(choices=[('mcq', 'Multiple Choice'), ('short', 'Short Answer')], max_length=50),
        ),
        migrations.AlterField(
            model_name='users',
            name='roleType',
            field=models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty'), ('admin', 'Admin')], max_length=20),
        ),
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('choiceID', models.AutoField(primary_key=True, serialize=False)),
                ('choiceText', models.TextField()),
                ('isCorrect', models.BooleanField(default=False)),
                ('questionID', models.ForeignKey(db_column='questionID', on_delete=django.db.models.deletion.CASCADE, to='users.questions')),
            ],
            options={
                'db_table': 'Choices',
            },
        ),
        migrations.CreateModel(
            name='StudentAnswers',
            fields=[
                ('answerID', models.AutoField(primary_key=True, serialize=False)),
                ('textAnswer', models.TextField(blank=True, null=True)),
                ('attemptID', models.ForeignKey(db_column='attemptID', on_delete=django.db.models.deletion.CASCADE, to='users.assessmentattempts')),
                ('questionID', models.ForeignKey(db_column='questionID', on_delete=django.db.models.deletion.CASCADE, to='users.questions')),
                ('selectedChoice', models.ForeignKey(blank=True, db_column='selectedChoice', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.choices')),
            ],
            options={
                'db_table': 'StudentAnswers',
            },
        ),
    ]
