# Generated by Django 6.0.3 on 2026-04-16 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_align_application_status_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentattempts',
            name='earnedPoints',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='assessmentattempts',
            name='gradingStatus',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('graded', 'Graded')], default='graded', max_length=20),
        ),
        migrations.AddField(
            model_name='assessmentattempts',
            name='maxPoints',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='studentanswers',
            name='awardedPoints',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='studentanswers',
            name='instructorFeedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentanswers',
            name='isCorrect',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assessmentattempts',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
